<a href="https://colab.research.google.com/github/yeyorg/Compuerta_OR_DL/blob/main/Compuertas_OR_y_XOR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Librerias**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
import tensorflow as tf 

# Datos

## Datos de entrenamiento para compuerta **OR**


<table align="left">
  <tr>
    <th>X1</th>
    <th>X2</th>
    <th>D</th>
  </tr>
  <tr>
    <th>0</th>
    <th>0</th>
    <th>0</th>
  </tr>
    <tr>
    <th>0</th>
    <th>1</th>
    <th>1</th>
  </tr>
  <tr>
    <th>1</th>
    <th>0</th>
    <th>1</th>
  </tr>
  <tr>
    <th>1</th>
    <th>1</th>
    <th>1</th>
  </tr>
</table>

In [2]:
x_train = np.array([  [0,0],  [0,1],  [1,0],  [1,1] ])
print(x_train)
y_train = np.array([0,1,1,1])
print(y_train)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[0 1 1 1]


## Datos de entrenamiento para compuerta **XOR**


<table align="left">
  <tr>
    <th>X1</th>
    <th>X2</th>
    <th>D</th>
  </tr>
  <tr>
    <th>0</th>
    <th>0</th>
    <th>0</th>
  </tr>
    <tr>
    <th>0</th>
    <th>1</th>
    <th>1</th>
  </tr>
  <tr>
    <th>1</th>
    <th>0</th>
    <th>1</th>
  </tr>
  <tr>
    <th>1</th>
    <th>1</th>
    <th>0</th>
  </tr>
</table>

In [3]:
XOR_train = np.array([  [0,0],  [0,1],  [1,0],  [1,1] ])
print(XOR_train)
y_XOR_train = np.array([0,1,1,0])
print(y_XOR_train)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[0 1 1 0]


#Definir las redes

## Definir el red **ADALINE**


In [4]:
def Sequential_model_ADALINE(learningRate):
  model_ADALINE = Sequential()
  model_ADALINE.add(Dense(1, input_shape=x_train.shape, activation='relu'))  

  opt = tf.keras.optimizers.Adam(learning_rate=learningRate) 
  model_ADALINE.compile(loss = 'mean_squared_error', optimizer=opt, metrics=['accuracy'])

  return model_ADALINE

##Definir la red **Superficial**

In [5]:
def Sequential_model_superficial(learningRate):
  model_superficial = Sequential()
  model_superficial.add(Dense(10, input_shape=x_train.shape, activation='relu'))  #Capa oculta
  model_superficial.add(Dense(1, activation='sigmoid'))  #Capa de salida

  opt = tf.keras.optimizers.Adam(learning_rate=learningRate) 
  model_superficial.compile(loss = 'mean_squared_error', optimizer=opt, metrics=['accuracy'])

  return model_superficial

# Red **ADALINE** learning rate = 0.01

In [6]:
model_ADALINE_001 = Sequential_model_ADALINE(0.01)

##  Entrenamiento 

In [ ]:
history =model_ADALINE_001.fit(x_train, y_train, epochs=500, verbose=2)
result_ADALINE_001 = model_ADALINE_001.predict(x_train)

# Resultados red **ADALINE** learning rate = 0.01
# 500 epocas

In [8]:
print(np.int8(result_ADALINE_001>0.5))

[[0]
 [1]
 [1]
 [1]]


# Red **ADALINE** learning rate = 0.001

In [23]:
model_ADALINE_0001 = Sequential_model_ADALINE(0.001)

## Entrenamiento

In [ ]:
history = model_ADALINE_0001.fit(x_train, y_train, epochs=1000, verbose=2)
result_ADALINE_0001 = model_ADALINE_0001.predict(x_train)

# Resultados red **ADALINE** learning rate = 0.001
# 1000 Epocas

In [25]:
print(np.int8(result_ADALINE_0001>0.5))

[[0]
 [1]
 [1]
 [1]]


# Red **ADALINE** learning rate = 0.0045

In [28]:
model_ADALINE_00045 = Sequential_model_ADALINE(0.0045)

## Entrenamiento

In [ ]:
history = model_ADALINE_00045.fit(x_train, y_train, epochs=700, verbose=2)
result_ADALINE_00045 = model_ADALINE_00045.predict(x_train)

# Resultados red **ADALINE** learning rate = 0.0045
# 700 Epocas

In [30]:
print(np.int8(result_ADALINE_00045>0.5))

[[0]
 [1]
 [1]
 [1]]


# Compilación de la red **superficial** learning rate = 0.01

In [31]:
model_superficial_001 = Sequential_model_superficial(0.01)

##  Entrenamiento con 100 epocas

In [ ]:
history = model_superficial_001.fit(x_train, y_train, epochs=100, verbose=2)
result_superficial_001 = model_superficial_001.predict(x_train)

# Resultados red **superficial** learning rate =0.01
# 100 epocas

In [33]:
print(np.int8(result_superficial_001>0.5))

[[0]
 [1]
 [1]
 [1]]
