<a href="https://colab.research.google.com/github/yeyorg/Compuerta_OR_DL/blob/main/OR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Librerias**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
import tensorflow as tf 

### Datos de entrenamiento para compuerta **OR**


<table align="left">
  <tr>
    <th>X1</th>
    <th>X2</th>
    <th>D</th>
  </tr>
  <tr>
    <th>0</th>
    <th>0</th>
    <th>0</th>
  </tr>
    <tr>
    <th>0</th>
    <th>1</th>
    <th>1</th>
  </tr>
  <tr>
    <th>1</th>
    <th>0</th>
    <th>1</th>
  </tr>
  <tr>
    <th>1</th>
    <th>1</th>
    <th>1</th>
  </tr>
</table>

In [ ]:
x_train = np.array([  [0,0],  [0,1],  [1,0],  [1,1] ])
print(x_train)
y_train = np.array([0,1,1,1])
print(y_train)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[0 1 1 1]


### Definir el red **ADALINE**


In [ ]:
def Sequential_model(learningRate):
  model = Sequential()
  model.add(Dense(1, input_shape=x_train.shape, activation='relu'))  

  opt = tf.keras.optimizers.Adam(learning_rate=learningRate) 
  model.compile(loss = 'mean_squared_error', optimizer=opt, metrics=['accuracy'])

  return model

### Compilación de la red **ADALINE** learning rate = 0.01

In [ ]:
model = Sequential_model(0.01)

##  Entrenamiento con 300 epocas

In [ ]:
history = model.fit(x_train, y_train, epochs=300, verbose=2)

### Resultados learning rate = 1, epochs = 300

In [ ]:
result = model.predict(x_train)

In [ ]:
print(np.int8(result>0.5))

[[0]
 [1]
 [1]
 [1]]
