<a href="https://colab.research.google.com/github/yeyorg/Compuerta_OR_DL/blob/main/OR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Librerias**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
import tensorflow as tf 

### Datos de entrenamiento para compuerta **OR**


<table align="left">
  <tr>
    <th>X1</th>
    <th>X2</th>
    <th>D</th>
  </tr>
  <tr>
    <th>0</th>
    <th>0</th>
    <th>0</th>
  </tr>
    <tr>
    <th>0</th>
    <th>1</th>
    <th>1</th>
  </tr>
  <tr>
    <th>1</th>
    <th>0</th>
    <th>1</th>
  </tr>
  <tr>
    <th>1</th>
    <th>1</th>
    <th>1</th>
  </tr>
</table>

In [2]:
x_train = np.array([  [0,0],  [0,1],  [1,0],  [1,1] ])
print(x_train)
y_train = np.array([0,1,1,1])
print(y_train)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[0 1 1 1]


### Definir el red **ADALINE**


In [3]:
def Sequential_model_ADALINE(learningRate):
  model = Sequential()
  model.add(Dense(1, input_shape=x_train.shape, activation='relu'))  

  opt = tf.keras.optimizers.Adam(learning_rate=learningRate) 
  model.compile(loss = 'mean_squared_error', optimizer=opt, metrics=['accuracy'])

  return model

### Compilación de la red **ADALINE** learning rate = 0.01

In [13]:
model = Sequential_model_ADALINE(0.01)

##  Entrenamiento con 300 epocas

In [14]:
history = model.fit(x_train, y_train, epochs=300, verbose=2)

Epoch 1/300
1/1 - 0s - loss: 0.5424 - accuracy: 0.5000
Epoch 2/300
1/1 - 0s - loss: 0.5384 - accuracy: 0.5000
Epoch 3/300
1/1 - 0s - loss: 0.5347 - accuracy: 0.5000
Epoch 4/300
1/1 - 0s - loss: 0.5293 - accuracy: 0.5000
Epoch 5/300
1/1 - 0s - loss: 0.5149 - accuracy: 0.5000
Epoch 6/300
1/1 - 0s - loss: 0.4997 - accuracy: 0.5000
Epoch 7/300
1/1 - 0s - loss: 0.4844 - accuracy: 0.5000
Epoch 8/300
1/1 - 0s - loss: 0.4692 - accuracy: 0.5000
Epoch 9/300
1/1 - 0s - loss: 0.4543 - accuracy: 0.5000
Epoch 10/300
1/1 - 0s - loss: 0.4399 - accuracy: 0.5000
Epoch 11/300
1/1 - 0s - loss: 0.4262 - accuracy: 0.5000
Epoch 12/300
1/1 - 0s - loss: 0.4130 - accuracy: 0.5000
Epoch 13/300
1/1 - 0s - loss: 0.4005 - accuracy: 0.5000
Epoch 14/300
1/1 - 0s - loss: 0.3888 - accuracy: 0.5000
Epoch 15/300
1/1 - 0s - loss: 0.3778 - accuracy: 0.5000
Epoch 16/300
1/1 - 0s - loss: 0.3675 - accuracy: 0.5000
Epoch 17/300
1/1 - 0s - loss: 0.3580 - accuracy: 0.5000
Epoch 18/300
1/1 - 0s - loss: 0.3492 - accuracy: 0.5000
E

### Resultados learning rate = 0.01, epochs = 300

In [ ]:
result = model.predict(x_train)

In [16]:
print(np.int8(result>0.5))

[[0]
 [1]
 [1]
 [1]]


### Definir el red **superficial**

In [17]:
def Sequential_model_superficial(learningRate):
  model_superficial = Sequential()
  model_superficial.add(Dense(1, input_shape=x_train.shape, activation='relu'))  

  opt = tf.keras.optimizers.Adam(learning_rate=learningRate) 
  model_superficial.compile(loss = 'mean_squared_error', optimizer=opt, metrics=['accuracy'])

  return model_superficial

### Compilación de la red **superficial** learning rate = 0.01

In [22]:
model = Sequential_model_superficial(0.01)

##  Entrenamiento con 300 epocas

In [ ]:
history = model.fit(x_train, y_train, epochs=300, verbose=2)