<a href="https://colab.research.google.com/github/yeyorg/Compuerta_OR_DL/blob/main/OR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Librerias**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
import tensorflow as tf 

### Datos de entrenamiento para compuerta **OR**


<table align="left">
  <tr>
    <th>X1</th>
    <th>X2</th>
    <th>D</th>
  </tr>
  <tr>
    <th>0</th>
    <th>0</th>
    <th>0</th>
  </tr>
    <tr>
    <th>0</th>
    <th>1</th>
    <th>1</th>
  </tr>
  <tr>
    <th>1</th>
    <th>0</th>
    <th>1</th>
  </tr>
  <tr>
    <th>1</th>
    <th>1</th>
    <th>1</th>
  </tr>
</table>

In [2]:
x_train = np.array([  [0,0],  [0,1],  [1,0],  [1,1] ])
print(x_train)
y_train = np.array([0,1,1,1])
print(y_train)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[0 1 1 1]


### Definir el red **ADALINE**


In [3]:
def Sequential_model_ADALINE(learningRate):
  model = Sequential()
  model.add(Dense(1, input_shape=x_train.shape, activation='relu'))  

  opt = tf.keras.optimizers.Adam(learning_rate=learningRate) 
  model.compile(loss = 'mean_squared_error', optimizer=opt, metrics=['accuracy'])

  return model

### Compilación de la red **ADALINE** learning rate = 0.01

In [13]:
model = Sequential_model_ADALINE(0.01)

###  Entrenamiento con 300 epocas

In [ ]:
history = model.fit(x_train, y_train, epochs=300, verbose=2)

### Resultados learning rate = 0.01, epochs = 300

In [ ]:
result = model.predict(x_train)

In [30]:
print(np.int8(result>0.5))

[[0]
 [1]
 [1]
 [1]]


### Definir el red **superficial**

In [31]:
def Sequential_model_superficial(learningRate):
  model_superficial = Sequential()
  model_superficial.add(Dense(10, input_shape=x_train.shape, activation='relu'))  #Capa oculta
  model_superficial.add(Dense(1, activation='sigmoid'))  #Capa de salida

  opt = tf.keras.optimizers.Adam(learning_rate=learningRate) 
  model_superficial.compile(loss = 'mean_squared_error', optimizer=opt, metrics=['accuracy'])

  return model_superficial

### Compilación de la red **superficial** learning rate = 0.01

In [33]:
model_superficial = Sequential_model_superficial(0.01)

##  Entrenamiento con 200 epocas

In [ ]:
history = model_superficial.fit(x_train, y_train, epochs=200, verbose=2)

### Resultados red **superficial** learning rate =0.01, epochs = 200

In [ ]:
result_superficial = model_superficial.predict(x_train)

In [36]:
print(np.int8(result_superficial>0.5))

[[0]
 [1]
 [1]
 [1]]
